publish_mode: editorial_workflow
backend:
  name: github
  repo: rivnatmalsa/gt3docs
  base_url: https://9ud4hnm18f.execute-api.us-east-1.amazonaws.com
  auth_endpoint: /prod/auth
site_id: http://docs-portal-gt3.s3-website-us-east-1.amazonaws.com/
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/posts"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured image", name: "thumbnail", widget: "image" }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          default: ["news"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
